version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExtprojectabhkProject
  gitServerName: abhk
  gitUrl: https://github.com/ak879753
  gitUsername: ak879753
  gitBranch: main
- name: AbhiPackages
  gitServerName: abhk
  gitUrl: https://github.com/ak879753
  gitUsername: ak879753
  gitBranch: main
